version: "3.11"
services:
  litellm:
    build:
      context: .
      args:
        target: runtime
    image: ghcr.io/berriai/litellm:main-stable
    #########################################
    ## Uncomment these lines to start proxy with a config.yaml file ##
    volumes:
     - ./config.yaml:/app/config.yaml
    # The below two are my suggestion
    command:
     - "--config=/app/config.yaml"
     - "--port=4000"
     - "num_workers=8"
    ##############################################
    #########################################
    ## Uncomment these lines to start proxy with a config.yaml file ##
    # volumes:
    ###############################################
    networks:
      - dokploy-network
    labels:
      - traefik.enable=true
      - traefik.http.routers.${HASH}.entrypoints=websecure
      - traefik.http.routers.${HASH}.tls.certResolver=cloudflare
      - traefik.http.routers.${HASH}.rule=Host(`${PROXY_HOST}`)
      - traefik.http.services.${HASH}.loadbalancer.server.port=${PROXY_PORT}
  
networks:
  dokploy-network:
    external: true

# ...rest of your docker-compose config if any
