version: "3.11"
services:
  litellm:
    build:
      context: .
      args:
        target: runtime
    image: ghcr.io/berriai/litellm:main-stable
    #########################################
    ## Uncomment these lines to start proxy with a config.yaml file ##
    volumes:
     - ./config.yaml:/app/config.yaml
    # The below two are my suggestion
    # command:
    #  - "--config=/app/config.yaml"
    ##############################################
    #########################################
    ## Uncomment these lines to start proxy with a config.yaml file ##
    # volumes:
    ###############################################
    environment:
        DATABASE_URL: "${DATABASE_URL}"
        STORE_MODEL_IN_DB: "True" # allows adding models to proxy via UI
    networks:
      - dokploy-network
  
  prometheus:
    image: prom/prometheus
    volumes:
      - prometheus_data:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=15d'
    restart: unless-stopped
    networks:
      - dokploy-network

volumes:
  prometheus_data: {}

networks:
  dokploy-network:
    external: true

# ...rest of your docker-compose config if any
