version: "3.11"
services:
  litellm:
    build:
      context: .
      args:
        target: runtime
    image: ghcr.io/berriai/litellm:main-stable
    #########################################
    ## Uncomment these lines to start proxy with a config.yaml file ##
    volumes:
     - ./config.yaml:/app/config.yaml
    # The below two are my suggestion
    command:
     - "--config=/app/config.yaml"
     - "--port=${PROXY_PORT}"
     - "--num_workers=${NUM_WORKERS}"
    ##############################################
    #########################################
    ## Uncomment these lines to start proxy with a config.yaml file ##
    # volumes:
    ###############################################
    networks:
      - dokploy-network
    expose:
      - ${PROXY_PORT}
    env_file:
      - .env

    labels:
      - traefik.enable=true
      - traefik.http.routers.${HASH}.entrypoints=websecure
      - traefik.http.routers.${HASH}.tls.certResolver=cloudflare
      - traefik.http.routers.${HASH}.rule=Host(`${PROXY_HOST}`)
      - traefik.http.services.${HASH}.loadbalancer.server.port=${PROXY_PORT}
      - traefik.http.routers.${HASH}.service=${HASH}
      - traefik.http.routers.${HASH}.middlewares=${HASH}-timeout
      - traefik.http.middlewares.${HASH}-timeout.idleTimeout=600s
      - traefik.http.middlewares.${HASH}-timeout.sendTimeout=600s
      - traefik.http.middlewares.${HASH}-timeout.readTimeout=600s

  
networks:
  dokploy-network:
    external: true

# ...rest of your docker-compose config if any
